name:                studies
version:             0.1.0.0
github:              "pcrbrandao/studies"
license:             BSD-3-Clause
author:              "Pedro Brandao"
maintainer:          "pcrbrandao@gmail.com"
copyright:           "free"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pcrbrandao/studies#readme>

dependencies:
- base >= 4.7 && < 5
- splitmix
- primitive
- transformers-compat
- MonadRandom
- random
- random-shuffle

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  studies-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - studies

tests:
  studies-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - studies
    - QuickCheck
